### ISSUE TITLE
Stop words

### ISSUE THREAD

**Issue by yekayra** [twhiteaker/Lunr-Index-and-Search-for-Static-Sites#3]
Dear BLE-LETR
Your repisotiry saved my life. Thank you very much. After too many searching finally I found how to build an index for a js search engine. I built index and tested it and it worked. (It was a kind of magic for me.) 
I have an another problem. ( I am new in js and node). My index is built in Turkish and I need a code that eleminate words (stop words) which are not important and one or two digits number. This kind of words and numbers expand my index.
Sorry for my English.
Thank you very much again.
Sincerly.

**Comment by twhiteaker** [comment]
Lunr documentation describes multi-language support:
https://lunrjs.com/guides/language_support.html

However, Turkish is not currently supported.  So I think what you would do is specify the Turkish stop words in a custom pipeline. Pipelines are described here but not in great detail:
https://lunrjs.com/guides/customising.html#pipeline-functions

Apparently lunr.generateStopWordFilter "builds a stopWordFilter function from the provided list of stop words."  So I think the tools you need are there, though I don't know how to put it together for you. As this is a Lunr issue, I suggest asking the Lunr developers how to go about it.
