### ISSUE TITLE
Search ca has no results while cat has!

### ISSUE THREAD

**Issue by emersonbottero** [twhiteaker/Lunr-Index-and-Search-for-Static-Sites#5]
Is there a setting or something we can do to make it work?

the difference between cat an ca is small but I would expect 'auth' to return result, I need to at least type 'authent' to sow some results but for the user is easy to think the search is not working at all.

P.S.: Thank you very much for the example.. I would struggle a lot without it.  :smile:

**Comment by twhiteaker** [comment]
I don't know of a setting, but you could enter `ca*` or `auth*` to get results according to [lunr wildcard functionality](https://lunrjs.com/guides/searching.html#wildcards).

**Comment by emersonbottero** [comment]
worked like a charm...
thanks
